version: "3.7"
services:
  testdataserver:
    build: .
    ports:
      - 80:8000
    volumes:
      - ./db:/db
  robottests:
    build: robottests
    depends_on:
      - testdataserver
    environment:
      BASE_URL: http://testdataserver:8000
      ROBOT_OPTIONS: ""
    volumes:
      - ./robottests/output:/robottests/output
