# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "robottests/requirements.txt" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
          name: Build unittest Docker images
          command: docker build -f Dockerfile-tests -t unittests .

    - run:
          name: Run unittest Docker container
          command: docker run unittests

    - run:
          name: Build Test Data Server and Robot test Docker images
          command: docker-compose build
        
    - run:
          name: Run Robot tests
          command: docker-compose run --rm robottests

    - store_artifacts:
        path: tests/output
        destination: unittests/

    - store_artifacts:
        path: robottests/output
        destination: robottests/
