# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "server/requirements.txt" }}-{{ checksum "tests/requirements.txt" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r server/requirements.txt -r tests/requirements.txt
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "server/requirements.txt" }}-{{ checksum "tests/requirements.txt" }}

    - run:
        name: run flake8
        command: |
          . venv/bin/activate
          flake8 .
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          export PYTHONPATH=server
          pytest

    - run:
          name: Build Test Data Server and Robot test Docker images
          command: docker-compose build
        
    - run:
          name: Run Robot tests
          command: docker-compose run --rm robottests

    - store_artifacts:
        path: test-reports
        destination: test-reports

    - store_artifacts:
        path: robottests/output
        destination: robottests/
