swagger: "2.0"
info:
  description: Test data server REST API documentation
  version: "0.0.1"
  title: Swagger for Test data server
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /status:
    get:
      operationId: "status.read"
      tags:
        - "Status"
      summary: "Server status"
      description: "Get server status to see if it is running"
      responses:
        200:
          description: "Server is running"
  /testdata:
    get:
      operationId: "testdata.read"
      tags:
      - "Testdata"
      summary: "Get test data"
      description: "Get data that can be used in test execution"
      responses:
        200:
          description: "Successful request of test data"
          schema:
            type: string
            properties:
              testdata:
                type: "string"
  /testdata/all:
    get:
      operationId: "testdata.read_all"
      tags:
      - "Testdata/all"
      summary: "Get all test data"
      description: "Get all test data which has been configured. Does not reserve test items for test execution."
      responses:
        200:
          description: "Successful request of all test data"
          schema:
            type: string
            properties:
              testdata:
                type: "string"
