openapi: "3.0.0"
info:
  description: Test data server REST API documentation
  version: "0.0.1"
  title: Swagger for Test data server

paths:
  /api/v1/status:
    get:
      operationId: "status.get_status"
      tags:
        - "Status"
      summary: "Server status"
      description: "Get server status to see if it is running"
      responses:
        200:
          description: "Server is running"
  /api/v1/testdata:
    get:
      operationId: "testdata.get_testdata"
      tags:
      - "Testdata"
      summary: "Get all test data"
      description: "Get all test data which has been configured. Does not reserve test items for test execution."
      responses:
        200:
          description: "Successful request of all test data"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - testdata
                  properties:
                    testdata:
                      type: string
    post:
      operationId: "testdata.post_dataset"
      description: Create new dataset
      tags:
      - "Testdata"
      summary: Create dataset
      requestBody:
        content:
          application/json:
            schema:
              required:
                - dataset
                - items
                - datatype
              properties:
                dataset:
                  type: string
                  description: Name of dataset to create
                items:
                  type: array
                  description: Items for dataset
                datatype:
                  type: string
                  description: Dataset type. Supported values - next, random
      responses:
        201:
          description: "Successfully created dataset."

  /api/v1/testdata/{dataset}:
    get:
      operationId: "testdata.get_testdata_next"
      tags:
      - "Testdata"
      summary: "Get test data"
      description: "Get data that can be used in test execution."
      parameters:
        - name: dataset
          in: path
          required: true
          description: Dataset from which test data item is requested
          schema:
            type: string
      responses:
        200:
          description: "Successful request of test data"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - testdata
                  properties:
                    testdata:
                      type: string
    delete:
      operationId: "testdata.delete_dataset"
      description: Delete dataset from comfiguration
      tags:
      - "Testdata"
      summary: Delete dataset
      parameters:
        - name: dataset
          description: Dataset name
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Successful dataset deletion"
  /api/v1/testdata/{dataset}/{item}:
    delete:
      operationId: "testdata.delete_dataset_item"
      description: Delete dataset item from comfiguration
      tags:
      - "Testdata"
      summary: Delete dataset item
      parameters:
        - name: dataset
          description: Dataset name
          in: path
          required: true
          schema:
            type: string
        - name: item
          description: Dataset item
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Successful dataset item deletion"
    post:
      operationId: "testdata.post_dataset_item"
      description: Add new dataset item
      tags:
      - "Testdata"
      summary: Add dataset item
      parameters:
        - name: dataset
          description: Dataset name
          in: path
          required: true
          schema:
            type: string
        - name: item
          description: Dataset item
          in: path
          required: true
          schema:
            type: string
      responses:
        201:
          description: "Successfully added item."
